name: Cancel Workflows

on: [push]

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel all workflows
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel
